[[redirects]]
  from = "/movie/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/show/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/person/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["build/index.html"]