export * from './Ids';
export * from './ImgConfig';
export * from './People';
export * from './Person';
export * from './Popular';
export * from './ItemType';
export * from './Movie';
export * from './Show';
export * from './Translation';
