export * from './Ids';
export * from './IImgConfig';
export * from './IPeople';
export * from './IPerson';
export * from './IPopular';
export * from './ItemType';
export * from './Movie';
export * from './Show';
export * from './Translation';
