name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to now
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
        with:
          clean: false
          repository: pouyio/twiso
          ref: refs/heads/master
      - name: ZEIT Now Deployment
        uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-args: '--prod'
          now-org-id: ${{ secrets.NOW_ORG_ID }}
          now-project-id: ${{ secrets.NOW_PROJECT_ID }}

  createSentryRelease:
    name: Add Sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: twiso
          SENTRY_PROJECT: twiso
        with:
          tagName: ${{ github.ref }}
          environment: prod
