name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to now
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
        with:
          clean: false
          repository: pouyio/twiso
          ref: refs/heads/master
      - name: Build artifact
        run: npm run build
      - name: Vercel Now Deployment
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  createSentryRelease:
    name: Add Sentry release
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Create a Sentry.io release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: twiso
          SENTRY_PROJECT: twiso
        with:
          version: ${{ github.event.release.tag_name }}
          environment: prod
          sourcemaps: './build'
