name: CI

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TWISO_DEPLOY_TOKEN }}
        run: bunx semantic-release
