name: Release and deploy
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TWISO_DEPLOY_TOKEN }}
        run: npx semantic-release
      - name: Checkout the repository
        uses: actions/checkout@v1
        with:
          clean: false
          repository: pouyio/twiso
          ref: refs/heads/master
      - name: ZEIT Now Deployment
        uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-args: '--prod'
          now-org-id: ${{ secrets.NOW_ORG_ID }}
          now-project-id: ${{ secrets.NOW_PROJECT_ID }}
