name: CI

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TWISO_DEPLOY_TOKEN }}
        run: npx semantic-release
