name: Create Sentry release

on:
  release:
    types: [published]

jobs:
  createSentryRelease:
    name: Add Sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: twiso
          SENTRY_PROJECT: twiso
        with:
          tagName: ${{ github.ref }}
          environment: prod
